//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPICRUD.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        public int id_estudiante { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int cedula { get; set; }
        public int edad { get; set; }
        public System.DateTime fech_nac { get; set; }
        public int telefono { get; set; }
        public string email { get; set; }
    }
}
